Repository benj652/TAHours, pull requests merged in 2025-05, with the labels that each got.

#166 Analytics page bugs fixed
  frontend/src/components/analytics/classManagement/ClassList.tsx
  frontend/src/components/analytics/middleCol/MiddleCol.tsx
  frontend/src/components/analytics/middleCol/TextAnalytics.tsx
  frontend/src/components/analytics/middleCol/TicketDisplay.tsx
  frontend/src/components/analytics/middleCol/TicketQueue.tsx
  frontend/src/hooks/taQueue/useGetClassQueues.ts
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
  frontend/src/types/taQueue.ts
Labels: build

#167 Real time final
  backend/controllers/user_controller.go
  backend/models/consts.go
  backend/socket/socket_server.go
  frontend/src/context/SocketContext.tsx
  frontend/src/hooks/general/useListenMainPage.ts
  frontend/src/types/socketEvents.ts
  frontend/src/types/users.ts
Labels: enhancement, build

#170 Additional documentation for all analytics components
  frontend/src/components/analytics/AnalyticPieChart.tsx
  frontend/src/components/analytics/classManagement/AddClassForm.tsx
  frontend/src/components/analytics/classManagement/ClassList.tsx
  frontend/src/components/analytics/middleCol/MiddleCol.tsx
  frontend/src/components/analytics/middleCol/SearchFilter.tsx
  frontend/src/components/analytics/middleCol/TextAnalytics.tsx
  frontend/src/components/analytics/middleCol/TicketDisplay.tsx
  frontend/src/components/analytics/middleCol/TicketQueue.tsx
  frontend/src/components/analytics/middleCol/ticketpopupanal.tsx
  frontend/src/components/analytics/roleAssigning/RoleChangePopup.tsx
  frontend/src/components/analytics/roleAssigning/SearchableDropdown.tsx
  frontend/src/store/localStores/analyticsPageStore.ts
Labels: documentation

#171 Readme update
  README.md
  backend/README.md
  frontend/.env.example
  frontend/README.md
  public/er_diagram.png
  public/system_design.png
  public/tech_stack.png
Labels: documentation

#172 Added middleware to class routes
  backend/controllers/cs_class_controller.go
  backend/routes/cs_class_router.go
Labels: bug, enhancement, build

#169 thread documentation
  backend/controllers/cs_class_controller.go
  backend/routes/cs_class_router.go
  frontend/src/components/analytics/classManagement/AddClassForm.tsx
  frontend/src/components/analytics/classManagement/ClassList.tsx
  frontend/src/components/feed/Post.tsx
  frontend/src/components/feed/Posts.tsx
  frontend/src/components/feed/Replies.tsx
  frontend/src/components/feed/Reply.tsx
  frontend/src/components/feed/WritePost.tsx
  frontend/src/components/feed/WriteReply.tsx
  frontend/src/components/feed/index.tsx
  frontend/src/hooks/csClass/index.ts
  frontend/src/hooks/csClass/useDeactivateClass.ts
  frontend/src/types/networking.ts
Labels: documentation

#173 Added some nice docs to the pages
  frontend/src/components/mainPage/TaQueue.tsx
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
  frontend/src/pages/feedPage/FeedPage.tsx
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/mainPage/MainPage.tsx
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: documentation

#174 Documention for profile and navbar components
  frontend/src/components/navbar/NavBar.tsx
  frontend/src/components/navbar/NavBarButton.tsx
  frontend/src/components/profile/StudentTickets.tsx
  frontend/src/components/profile/TicketPopup.tsx
Labels: documentation

#175 middleware for route
  backend/controllers/cs_class_controller.go
  backend/routes/cs_class_router.go
Labels: documentation

#180 Docs for the stores
  frontend/src/store/globalStores/csClassStore.ts
  frontend/src/store/globalStores/taQueueStore.ts
  frontend/src/store/globalStores/threadStore.ts
  frontend/src/store/globalStores/ticketStore.ts
  frontend/src/store/globalStores/userStore.ts
  frontend/src/store/localStores/analyticsPageStore.ts
  frontend/src/store/localStores/forceUpdateStore.ts
  frontend/src/store/localStores/mainPageStore.ts
  frontend/src/store/localStores/threadStore.ts
Labels: documentation

#179 Documentation for frontend utils
  frontend/src/utils/classNames.ts
  frontend/src/utils/dateFormatters.ts
  frontend/src/utils/httpClient.ts
Labels: documentation

#176 Added Documentation to half of main page components
  frontend/src/components/mainPage/TaQueue.tsx
  frontend/src/components/mainPage/addTaQueue/AddTaQueueButton.tsx
  frontend/src/components/mainPage/addTaQueue/AddTaQueuePopup.tsx
  frontend/src/components/mainPage/taCard/ActiveTa.tsx
  frontend/src/components/mainPage/taCard/ActiveTas.tsx
  frontend/src/components/mainPage/taCard/JoinSessionButton.tsx
  frontend/src/components/mainPage/taCard/LeaveSessionButton.tsx
Labels: documentation

#177 documentation for main page
  frontend/src/components/mainPage/queueCard/AddTicketButton.tsx
  frontend/src/components/mainPage/queueCard/Ticket.tsx
  frontend/src/components/mainPage/queueCard/Tickets.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/QueuePopup.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
Labels: documentation

#178 Added documentation to hooks, most were already good
  frontend/src/hooks/csClass/useGetCSClass.ts
  frontend/src/hooks/taQueue/useGetClassQueues.ts
  frontend/src/hooks/tickets/useGetTicket.ts
  frontend/src/hooks/tickets/useResolveTicket.ts
  frontend/src/hooks/tickets/useUserTickets.ts
Labels: documentation

#181 Extended documentation on useListenMainPage.ts
  frontend/src/hooks/general/useListenMainPage.ts
Labels: documentation

#182 Added documents to taQueue.ts, tickets.ts, and users.ts
  frontend/src/types/taQueue.ts
  frontend/src/types/tickets.ts
  frontend/src/types/users.ts
Labels: documentation

#184 Documentation Headers
  frontend/src/hooks/csClass/useCreateCSClass.ts
  frontend/src/hooks/csClass/useDeactivateClass.ts
  frontend/src/hooks/csClass/useGetActiveClasses.ts
  frontend/src/hooks/csClass/useGetCSClass.ts
  frontend/src/hooks/csClass/userCreateTaQueue.ts
  frontend/src/hooks/posts/useCreateComment.ts
  frontend/src/hooks/posts/useCreatePost.ts
  frontend/src/hooks/posts/useDeletePost.ts
  frontend/src/hooks/posts/useGetAllPosts.ts
  frontend/src/hooks/taQueue/useGetAllTaQueues.ts
Labels: documentation

#185 fxied weird bug with comment and deleted html tag
  frontend/src/components/mainPage/TaQueue.tsx
  frontend/src/store/localStores/mainPageStore.ts
Labels: bug

#186 Fixed bug with sessions not display correctly
  frontend/src/components/analytics/middleCol/TextAnalytics.tsx
Labels: bug

#187 Made link to tutorial video
  frontend/src/pages/mainPage/MainPage.tsx
  frontend/src/types/misc.ts
Labels: documentation, build

#188 MADE THE TITLE ON THE TAB FINALLY
  frontend/index.html
  frontend/public/colbyseal.svg
Labels: enhancement
