Repository benj652/TAHours, pull requests merged in 2025-02, with the labels that each got.

#21 Moved the .env file from the root to the backend (updating files acco…
  README.md
  backend/.env.example
  backend/cmd/server/main.go
Labels: documentation, build

#20 Frontend setup
  .vscode/extensions.json
  frontend/.prettierignore
  frontend/package-lock.json
  frontend/package.json
  frontend/prettierrc.yaml
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/utils/classNames.ts
  frontend/src/utils/index.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: build

#29 CSS Fixed
  frontend/src/index.css
Labels: build

#31 Essential Assets for Development
  frontend/src/assets/colbyseal.svg
  frontend/src/assets/colbytext.svg
Labels: build

#32 Added basic file for each page and implemented url router
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/analytics/index.ts
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
  frontend/src/pages/analyticsPage/index.ts
  frontend/src/pages/feed/index.ts
  frontend/src/pages/feedPage/FeedPage.tsx
  frontend/src/pages/feedPage/index.ts
  frontend/src/pages/index.ts
  frontend/src/pages/login/index.ts
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/loginPage/index.ts
  frontend/src/pages/main/index.ts
  frontend/src/pages/mainPage/MainPage.tsx
  frontend/src/pages/mainPage/index.ts
  frontend/src/pages/profile/index.ts
  frontend/src/pages/profilePage/ProfilePage.tsx
  frontend/src/pages/profilePage/index.ts
Labels: build

#37 Skeleton Profile Page
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: enhancement, build

#38 Made Epic Navbar
  frontend/src/App.tsx
  frontend/src/components/navbar/NavBar.tsx
  frontend/src/components/navbar/NavBarButton.tsx
  frontend/src/components/navbar/index.ts
  frontend/src/index.css
Labels: build

#41 Debugging
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/feed/Post.tsx
  frontend/src/components/feed/Posts.tsx
  frontend/src/components/feed/Replies.tsx
  frontend/src/components/feed/Reply.tsx
  frontend/src/components/feed/WritePost.tsx
  frontend/src/components/feed/WriteReply.tsx
  frontend/src/components/feed/index.tsx
  frontend/src/components/index.ts
  frontend/src/components/navbar/NavBar.tsx
  frontend/src/components/navbar/NavBarButton.tsx
  frontend/src/index.css
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
  frontend/src/pages/feedPage/FeedPage.tsx
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/mainPage/MainPage.tsx
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: bug

#42 made some fixes to the typescript config, wrote some basic hooks, wro…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/csClass/index.ts
  frontend/src/hooks/csClass/useCreateCSClass.ts
  frontend/src/hooks/csClass/useGetCSClass.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/posts/index.ts
  frontend/src/hooks/taQueue/index.ts
  frontend/src/hooks/tickets/index.ts
  frontend/src/hooks/user/index.ts
  frontend/src/store/index.ts
  frontend/src/types/csClass.ts
  frontend/src/types/index.ts
  frontend/src/types/posts.ts
  frontend/src/types/taQueue.ts
  frontend/src/types/tickets.ts
  frontend/src/types/users.ts
  frontend/src/utils/httpClient.ts
  frontend/src/utils/index.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: bug, build

#44 Frontend o auth
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/navbar/NavBar.tsx
  frontend/src/hooks/user/index.ts
  frontend/src/hooks/user/useLogin.ts
  frontend/src/hooks/user/useLogout.ts
  frontend/src/main.tsx
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/store/index.ts
  frontend/src/store/userStore.ts
  frontend/src/types/index.ts
  frontend/src/types/routes.ts
  frontend/src/vite-env.d.ts
Labels: build

#46 Ta View Mockup
  frontend/src/assets/star.svg
  frontend/src/pages/mainPage/MainPage.tsx
Labels: build

#60 Analytics Page
  backend/go.mod
  backend/go.sum
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/analytics/SearchableDropdown.tsx
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
Labels: build

#62 Final Main Page Connections
  backend/app/app.go
  backend/controllers/ticket_controller.go
  backend/models/ticket_model.go
  count_line.sh
  frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
  frontend/src/hooks/tickets/useCreateTicket.ts
  frontend/src/hooks/tickets/useResolveTicket.ts
  frontend/src/types/tickets.ts
Labels: build

#70 Made some hooks and imporved middleware for updating roles routes and…
  backend/controllers/user_controller.go
  backend/routes/user_router.go
  frontend/src/hooks/csClass/useCreateCSClass.ts
  frontend/src/hooks/user/useGetAllUsers.ts
  frontend/src/types/networking.ts
Labels: build

#72 Prof view connection and maybe ws start
  backend/app/app.go
  backend/controllers/cs_class_controller.go
  backend/controllers/post_controller.go
  backend/controllers/ta_queue_controller.go
  backend/controllers/ticket_controller.go
  backend/controllers/user_controller.go
  backend/go.mod
  backend/go.sum
  backend/middleware/user_middleware.go
  backend/models/consts.go
  backend/routes/user_router.go
  backend/socket/socket_server.go
  frontend/src/App.tsx
  frontend/src/components/analytics/AnalyticPieChart.tsx
  frontend/src/components/analytics/ClassList.tsx
  frontend/src/components/analytics/SearchFilter.tsx
  frontend/src/components/analytics/SearchableDropdown.tsx
  frontend/src/components/analytics/TextAnalytics.tsx
  frontend/src/components/analytics/classManagement/AddClassForm.tsx
  frontend/src/components/analytics/classManagement/ClassList.tsx
  frontend/src/components/analytics/classManagement/index.ts
  frontend/src/components/analytics/index.ts
  frontend/src/components/analytics/middleCol/MiddleCol.tsx
  frontend/src/components/analytics/middleCol/SearchFilter.tsx
  frontend/src/components/analytics/middleCol/TextAnalytics.tsx
  frontend/src/components/analytics/middleCol/TicketQueue.tsx
  frontend/src/components/analytics/middleCol/index.ts
  frontend/src/components/analytics/roleAssigning/RoleChangePopup.tsx
  frontend/src/components/analytics/roleAssigning/SearchableDropdown.tsx
  frontend/src/components/analytics/roleAssigning/index.ts
  frontend/src/components/feed/Posts.tsx
  frontend/src/components/feed/WritePost.tsx
  frontend/src/context/SocketContext.tsx
  frontend/src/context/index.ts
  frontend/src/hooks/csClass/useCreateCSClass.ts
  frontend/src/hooks/general/index.ts
  frontend/src/hooks/general/useListenMainPage.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/posts/index.ts
  frontend/src/hooks/posts/listeners/index.ts
  frontend/src/hooks/posts/listeners/useListenMessages.ts
  frontend/src/hooks/user/index.ts
  frontend/src/hooks/user/updateRoleHooks/index.ts
  frontend/src/hooks/user/updateRoleHooks/useUpdateRoleProfessor.ts
  frontend/src/hooks/user/updateRoleHooks/useUpdateRoleStudent.ts
  frontend/src/hooks/user/updateRoleHooks/useUpdateRoleTA.ts
  frontend/src/main.tsx
  frontend/src/pages/analyticsPage/AnalyticsPage.tsx
  frontend/src/pages/feedPage/FeedPage.tsx
  frontend/src/store/localStores/analyticsPageStore.ts
  frontend/src/store/localStores/index.ts
  frontend/src/types/csClass.ts
  frontend/src/types/networking.ts
  frontend/src/types/users.ts
  frontend/src/utils/dateFormatters.ts
  frontend/src/utils/index.ts
Labels: build
