Repository benj652/TAHours, pull requests merged in 2025-04, with the labels that each got.

#109 finshed the hook
  backend/controllers/user_controller.go
  frontend/src/hooks/user/index.ts
  frontend/src/hooks/user/useUpdateUserDesc.ts
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: build

#117 Production ready changes made from the VM.
  docker-compose.yml
  frontend/src/context/SocketContext.tsx
  frontend/src/types/socketEvents.ts
  frontend/vite.config.ts
Labels: build

#120 Analytics
  backend/controllers/ta_queue_controller.go
  backend/controllers/ticket_controller.go
  backend/models/ta_queue_model.go
  backend/routes/ta_queue_router.go
  frontend/src/components/analytics/AnalyticPieChart.tsx
  frontend/src/components/analytics/classManagement/ClassList.tsx
  frontend/src/components/analytics/middleCol/MiddleCol.tsx
  frontend/src/components/analytics/middleCol/SearchFilter.tsx
  frontend/src/components/analytics/middleCol/TextAnalytics.tsx
  frontend/src/components/analytics/middleCol/TicketDisplay.tsx
  frontend/src/components/analytics/middleCol/TicketQueue.tsx
  frontend/src/hooks/taQueue/index.ts
  frontend/src/hooks/taQueue/useGetClassQueues.ts
  frontend/src/hooks/tickets/useResolveTicket.ts
  frontend/src/store/localStores/analyticsPageStore.ts
  frontend/src/types/misc.ts
  frontend/src/types/networking.ts
  frontend/src/types/taQueue.ts
  frontend/src/types/tickets.ts
  frontend/src/utils/dateFormatters.ts
  frontend/src/utils/httpClient.ts
Labels: build

#124 Tickets can now only be viewed on the main page by TAs, professors, a…
  frontend/src/components/mainPage/queueCard/Ticket.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
  frontend/src/types/users.ts
Labels: bug, build

#128 Ticket type now properly updated by backend
  backend/controllers/ticket_controller.go
Labels: bug

#140 Fix attempt two
  frontend/src/App.tsx
  frontend/src/hooks/general/useListenMainPage.ts
Labels: bug

#147 UI Bug Fixes
  frontend/src/components/analytics/middleCol/MiddleCol.tsx
  frontend/src/components/mainPage/taCard/ActiveTas.tsx
  frontend/src/components/mainPage/taCard/JoinSessionButton.tsx
  frontend/src/components/mainPage/taCard/LeaveSessionButton.tsx
  frontend/src/hooks/general/useListenMainPage.ts
Labels: bug

#148 Made auto welcome message in the dump the app builds from
  database/mongo-dump/TAHours/posts.bson
  database/mongo-dump/TAHours/posts.metadata.json
  database/mongo-dump/TAHours/users.metadata.json
Labels: bug, enhancement

#151 Piechartcolors
  frontend/src/components/analytics/AnalyticPieChart.tsx
  frontend/src/components/analytics/middleCol/TicketDisplay.tsx
  frontend/src/components/analytics/middleCol/ticketpopupanal.tsx
Labels: enhancement, build

#155 Store removal
  frontend/src/components/mainPage/TaQueue.tsx
  frontend/src/components/mainPage/queueCard/AddTicketButton.tsx
  frontend/src/components/mainPage/queueCard/Ticket.tsx
  frontend/src/components/mainPage/queueCard/Tickets.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/AddTicketPopup.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/QueuePopup.tsx
  frontend/src/components/mainPage/queueCard/queuePopups/ResolveTicketPopup.tsx
  frontend/src/components/mainPage/taCard/ActiveTas.tsx
  frontend/src/components/mainPage/taCard/JoinSessionButton.tsx
  frontend/src/components/mainPage/taCard/LeaveSessionButton.tsx
  frontend/src/hooks/general/useListenMainPage.ts
  frontend/src/pages/mainPage/MainPage.tsx
  frontend/src/store/localStores/mainPageStore.ts
  frontend/src/types/taQueue.ts
Labels: bug

#161 Hides join session button for student
  frontend/src/components/mainPage/taCard/JoinSessionButton.tsx
Labels: bug, build

#163 Leave1000
  frontend/src/hooks/general/useListenMainPage.ts
Labels: bug

#164 Date is now in queue in backend
  backend/controllers/cs_class_controller.go
Labels: enhancement
